apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  kustomize.buildOptions: >-
    --enable-helm --load-restrictor LoadRestrictionsNone
  application.resourceTrackingMethod: annotation
  resource.compareoptions: |
    ignoreAggregatedRoles: true
