apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: homepage
  includeCRDs: true
  namespace: homepage
  repo: https://jameswynn.github.io/helm-charts
  releaseName: homepage
  valuesFile: values.yaml
