
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - prometheus.localhost
    tls:
    - secretName: prometheus-kube-prometheus-stack-selfsigned-cert
      hosts:
      - prometheus.localhost
      # persistentVolume:
      #   enabled: true
      #   existingClaim: prometheus-pvc
      # securityContext:
      #   fsGroup: 0
      #   runAsGroup: 0
      #   runAsNonRoot: false
      #   runAsUser: 0
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus-stack-persistence
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - grafana.localhost
    tls:
    - secretName: grafana-kube-prometheus-stack-selfsigned-cert
      hosts:
      - grafana.localhost
  # persistentVolume:
  #   enabled: true
  #   existingClaim: grafana-pvc
  # securityContext:
  #   fsGroup: 0
  #   runAsGroup: 0
  #   runAsNonRoot: false
  #   runAsUser: 0
