
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - prometheus.localhost
    tls:
    - secretName: prometheus-kube-prometheus-stack-selfsigned-cert
      hosts:
      - prometheus.localhost
  prometheusSpec:
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      runAsGroup: 0
      fsGroup: 0
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 25Gi
          selector:
            matchLabels:
              name: prometheus-stack-prometheus-pv
    # serviceMonitorNamespaceSelector: {} #to select all
    serviceMonitorNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: docker-registry
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

grafana:
  adminPassword: password
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - grafana.localhost
    tls:
    - secretName: grafana-kube-prometheus-stack-selfsigned-cert
      hosts:
      - grafana.localhost
  persistence:
    type: pvc
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 10Gi
    existingClaim: prometheus-stack-grafana-pvc
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
