
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - prometheus.localhost
    tls:
    - secretName: prometheus-kube-prometheus-stack-selfsigned-cert
      hosts:
      - prometheus.localhost
  prometheusSpec:
    securityContext:
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1002
      fsGroup: 1001
    storageSpec:
      volumeClaimTemplate:
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: prometheus-stack-persistence
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
prometheusOperator:
  admissionWebhooks:
    patch:
      securityContext:
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1002

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - grafana.localhost
    tls:
    - secretName: grafana-kube-prometheus-stack-selfsigned-cert
      hosts:
      - grafana.localhost
  # persistentVolume:
  #   enabled: true
  #   existingClaim: grafana-pvc
  # securityContext:
  #   fsGroup: 0
  #   runAsGroup: 0
  #   runAsNonRoot: false
  #   runAsUser: 0
