
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - prometheus.localhost
    tls:
    - secretName: prometheus-kube-prometheus-stack-selfsigned-cert
      hosts:
      - prometheus.localhost
  prometheusSpec:
    # securityContext:
    #   runAsUser: 0
    #   runAsNonRoot: false
    #   runAsGroup: 0
    #   fsGroup: 0
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 25Gi
          selector:
            matchLabels:
              name: prometheus-stack-pv
# prometheusOperator:
#   admissionWebhooks:
#     deployment:
#       securityContext:
#         runAsUser: 0
#         runAsNonRoot: false
#         runAsGroup: 0
#         fsGroup: 0
#     patch:
#       securityContext:
#         runAsUser: 0
#         runAsNonRoot: false
#         runAsGroup: 0

grafana:
  adminPassword: password
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - grafana.localhost
    tls:
    - secretName: grafana-kube-prometheus-stack-selfsigned-cert
      hosts:
      - grafana.localhost
  # persistentVolume:
  #   enabled: true
  #   existingClaim: grafana-pvc
  # securityContext:
  #   fsGroup: 0
  #   runAsGroup: 0
  #   runAsNonRoot: false
  #   runAsUser: 0
