apiVersion: k3d.io/v1alpha4
kind: Simple
ports:
- port: "10443:443"
  nodeFilters:
  - agent:0
- port: "10080:80"
  nodeFilters:
  - agent:0
volumes: # repeatable flags are represented as YAML lists
- volume: /home/mde/mlops-platform/volume:/volume-data
  nodeFilters:
  - server:0
  - agent:*
- volume: /home/mde/mlops-platform/registry-ca.pem:/etc/ssl/certs/registry-ca.pem
  nodeFilters:
  - server:0
  - agent:*
registries:
  config: |
    mirrors:
      k3d.registry:
        endpoint:
        - https://docker-registry.mlplatform:11443/
    configs:
      k3d.registry:
        auth:
          username: admin
          password: password
        tls:
          ca_file: "/etc/ssl/certs/registry-ca.pem"
hostAliases: # /etc/hosts style entries to be injected into /etc/hosts in the node containers and in the NodeHosts section in CoreDNS
- ip: 10.201.50.246
  hostnames:
  - docker-registry.mlplatform
