apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: docker-registry
  includeCRDs: true
  namespace: docker-registry
  repo: https://helm.twun.io
  version: 2.2.2
  releaseName: docker-registry
  valuesFile: values.yaml
patches:
- target:
    kind: Deployment
    name: docker-registry
  path: security-patch.yaml
