service:
  name: registry
ingress:
  enabled: true
  className: nginx
  path: /
  hosts:
  - docker-registry.mlplatform
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: cluster-issuer
  tls:
  - secretName: docker-registry-cert-secret
    hosts:
    - docker-registry.mlplatform

persistence:
  existingClaim: docker-registry-pvc
  accessMode: 'ReadWriteOnce'
  enabled: true
  size: 100Gi
storage: filesystem

secrets:
  # htpasswd -Bc ./htpasswd <user_name> then copy the contents of htpasswd file
  htpasswd: "admin:$2y$05$GuqDLRi/t2rPqiKxdPUG5.W1PX7wsJCpT1VV.88JrqY7Rbd5rB.Wm"

metrics:
  enabled: true
  port: 5001
  # Create a prometheus-operator servicemonitor
  serviceMonitor:
    enabled: true
  # prometheus-operator PrometheusRule defining alerting rules for a Prometheus instance
  prometheusRule:
    enabled: false
    labels: {}
    rules: {}

configData:
  http:
    debug:
      prometheus:
        enabled: true
        path: /metrics
