apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: loki
  includeCRDs: false
  namespace: loki
  repo: https://grafana.github.io/helm-charts
  releaseName: loki
  valuesFile: values-loki.yaml
- name: promtail
  includeCRDs: false
  namespace: promtail
  repo: https://grafana.github.io/helm-charts
  releaseName: promtail
  valuesFile: values-promtail.yaml
