apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- crds/monitoring.coreos.com_podmonitors.yaml
- crds/monitoring.coreos.com_probes.yaml
- crds/monitoring.coreos.com_servicemonitors.yaml
- crds/monitoring.grafana.com_grafanaagents.yaml
- crds/monitoring.grafana.com_integrations.yaml
- crds/monitoring.grafana.com_logsinstances.yaml
- crds/monitoring.grafana.com_metricsinstances.yaml
- crds/monitoring.grafana.com_podlogs.yaml
helmCharts:
- name: loki
  includeCRDs: false
  namespace: loki
  repo: https://grafana.github.io/helm-charts
  releaseName: loki
  valuesFile: values-loki.yaml
- name: promtail
  includeCRDs: false
  namespace: promtail
  repo: https://grafana.github.io/helm-charts
  releaseName: promtail
  valuesFile: values-promtail.yaml
