ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: mlflow.localhost
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - mlflow.localhost
    secretName: mlflow-selfsigned-cert

backendStore:
  databaseMigration: false
  databaseConnectionCheck: false
  postgres:
    enabled: true
    host: postgresql
    port: 5432
    database: "mlflow"
    user: "postgres"
    password: "password"
