ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: mlflow.localhost
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - mlflow.localhost
    secretName: mlflow-selfsigned-cert

backendStore:
  databaseMigration: false
  databaseConnectionCheck: false
  postgres:
    enabled: true
    host: postgresql
    port: 5432
    database: "mlflow"
    user: "postgres"
    password: "..." #overriden in mlflow-secret

artifactRoot:
  s3:
    enabled: true
    bucket: mlflow-artifacts

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: http://minio:9000
  MLFLOW_TRACKING_URI: http://localhost:5000

extraSecretNamesForEnvFrom:
- mlflow-secret

tracking:
  metrics:
    serviceMonitor:
      # -- When set true then use a ServiceMonitor to configure scraping
      enabled: true
      # -- When set true then use a service port. On default use a pod port.
      useServicePort: true
      # -- Set the namespace the ServiceMonitor should be deployed
      namespace: mlflow
      # -- Set how frequently Prometheus should scrape
      interval: 30s
      # -- Set path to mlflow telemtery-path
      telemetryPath: /metrics
      labels:
        release: prometheus
