ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: mlflow.localhost
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - mlflow.localhost
    secretName: mlflow-selfsigned-cert

backendStore:
  databaseMigration: false
  databaseConnectionCheck: false
  postgres:
    enabled: true
    host: postgresql
    port: 5432
    database: "mlflow"
    user: "postgres"
    password: "..." #overriden in mlflow-secret

artifactRoot:
  s3:
    enabled: true
    bucket: mlflow-artifacts

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: http://minio:9000
  MLFLOW_TRACKING_URI: http://localhost:5000

extraSecretNamesForEnvFrom:
- mlflow-secret
