apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dagster
resources:
- namespace.yaml
helmCharts:
- name: dagster
  repo: https://dagster-io.github.io/helm
  version: 1.5.2
  releaseName: dagster
  includeCRDs: true
  valuesFile: values.yaml
  namespace: dagster
