global:
  postgresqlSecretName: "dagster-postgresql-secret"
  # The DAGSTER_HOME env var is set by default on all nodes from this value
  dagsterHome: /home/vscode/example-project/dagster_home

generatePostgresqlPasswordSecret: false
postgresql:
  postgresqlUsername: testuser
  existingSecret: dagster-postgresql-secret
  postgresqlDatabase: testdb
  persistence:
    #na chybe v dagster postgres kontajneri
    #chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
    #treba nastavit dagster-postgres-pv/data folder na:
    #sudo chown -R 1001:1001 data
    #https://stackoverflow.com/questions/63924161/postgresql-container-not-starting-chmod-changing-permissions-of-bitnami-post
    existingClaim: dagster-postgres-pvc

dagster-user-deployments:
  enabled: true
  imagePullSecrets:
  - name: docker-registry-secret
  deployments:
  - name: "example-project"
    image:
      repository: k3d.registry/v2/example-project
      tag: 36 # SED-ANCHOR-DAGSTER-VERSION
      pullPolicy: Always
    dagsterApiGrpcArgs:
    - "-d"
    - "project_name"
    - "-m"
    - "project_name"
    port: 3030
    includeConfigInLaunchedRuns:
      enabled: true
    envConfigMaps:
    - name: dagster-config-map
    envSecrets:
    - name: dagster-secret
    volumeMounts:
    - name: dagster-dvc-config-secret
      mountPath: /home/vscode/example-project/.dvc/config
      subPath: config
    volumes:
    - name: dagster-dvc-config-secret
      secret:
        secretName: dagster-dvc-config-secret


dagsterWebserver:
  workspace:
    enabled: false
  volumeMounts:
  - name: dagster-webserver-volume
    mountPath: /home/vscode/example-project/dagster_home
  volumes:
  - name: dagster-webserver-volume
    persistentVolumeClaim:
      claimName: dagster-webserver-pvc
  envSecrets:
  - name: dagster-secret

dagsterDaemon:
  enabled: true
  volumeMounts:
  - name: dagster-daemon-volume
    mountPath: /home/vscode/example-project/dagster_home
  volumes:
  - name: dagster-daemon-volume
    persistentVolumeClaim:
      claimName: dagster-daemon-pvc
  runCoordinator:
    config:
      queuedRunCoordinator:
        # The maximum number of runs to allow to be running at once. Defaults to no limit.
        maxConcurrentRuns: 100
        dequeueIntervalSeconds: 1
        dequeueNumWorkers: 6
  envSecrets:
  - name: dagster-secret

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      envConfigMaps:
      - name: dagster-config-map
      envSecrets:
      - name: dagster-secret
      volumeMounts:
      - name: dagster-executors-volume
        mountPath: /home/vscode/example-project/dagster_home
        readOnly: false
      - name: dagster-dvc-config-secret
        mountPath: /home/vscode/example-project/.dvc/config
        subPath: config
      volumes:
      - name: dagster-executors-volume
        persistentVolumeClaim:
          claimName: dagster-executors-pvc
      - name: dagster-dvc-config-secret
        secret:
          secretName: dagster-dvc-config-secret
      runK8sConfig:
        podSpecConfig:
          nodeSelector:
            dagster-role: worker
