---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
resources:
  # vyzaduje explicitne vytvorenie namespace
  - namespace.yaml
helmCharts:
  - name: sealed-secrets
    includeCRDs: true
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.13.2
    releaseName: sealed-secrets
    valuesFile: values.yaml
