apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ingress.yaml
helmCharts:
- name: minio
  repo: https://charts.bitnami.com/bitnami
  releaseName: minio
  valuesFile: values.yaml
