apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: jenkins
  includeCRDs: true
  namespace: jenkins
  repo: https://charts.bitnami.com/bitnami
  version: 12.4.6
  releaseName: jenkins
  valuesFile: values.yaml
